### 1.

In [1]:
import numpy as np

### 2.

In [3]:
zero_array = np.zeros(10)

In [4]:
zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 3.

In [7]:
array = np.arange(1, 11)

In [10]:
item_size = array.itemsize

In [12]:
len_of_array = len(array) * item_size

In [13]:
len_of_array

40

### 4.

In [18]:
np.info(np. add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

### 5.

In [20]:
array = np.arange(10, 50)

### 6.

In [21]:
reverse_array = array[::-1]

In [22]:
reverse_array

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 7.

In [24]:
array = np.arange(9)

In [27]:
array = array.reshape(3, 3)

In [28]:
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 8.

In [32]:
array = np.array([1,2,0,0,4,0])

In [33]:
array.nonzero()

(array([0, 1, 4], dtype=int64),)

### 9.

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 10.

In [124]:
matrix_five = np.full((5,5), np.arange(0, 5, dtype='float'))

In [125]:
matrix_five

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### 11.

In [58]:
np.linspace(0, 1, 12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### 12.

In [84]:
array = np.random.rand(10)

In [85]:
array

array([0.63766459, 0.83341006, 0.23524131, 0.04964001, 0.30421097,
       0.35668508, 0.25290047, 0.71602107, 0.95075721, 0.27900328])

In [86]:
np.sort(array)

array([0.04964001, 0.23524131, 0.25290047, 0.27900328, 0.30421097,
       0.35668508, 0.63766459, 0.71602107, 0.83341006, 0.95075721])

### 13.

In [76]:
np.iinfo('int8')

iinfo(min=-128, max=127, dtype=int8)

In [77]:
np.iinfo('int32')

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [78]:
np.iinfo('int64')

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [80]:
np.finfo('float32')

finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)

In [81]:
np.finfo('float64')

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

### 14.

In [109]:
array = np.arange(10, dtype = 'float32')

In [110]:
array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [111]:
float_array = array.astype('int32')

In [112]:
float_array.dtype

dtype('int32')

### 15.

In [113]:
two_dim_array = np.arange(0, 25)

In [114]:
two_dim_array = two_dim_array.reshape((5, 5))

In [115]:
two_dim_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [117]:
two_dim_array.mean(axis=1)

array([ 2.,  7., 12., 17., 22.])

### 16.

In [144]:
array = np.random.randint(0, 10, (3, 3))

In [145]:
array

array([[5, 2, 5],
       [8, 8, 6],
       [7, 9, 1]])

In [146]:
array[array[:, 2].argsort()]

array([[7, 9, 1],
       [5, 2, 5],
       [8, 8, 6]])

### 17.

In [147]:
array = np.random.randint(0, 10, (3, 3))

In [148]:
array

array([[8, 2, 8],
       [7, 8, 2],
       [4, 3, 1]])

In [149]:
array[[0, 1]] = array[[1, 0]]

In [150]:
array

array([[7, 8, 2],
       [8, 2, 8],
       [4, 3, 1]])

### 18.

In [156]:
np.repeat([0, 1, 2], [2, 3, 1])

array([0, 0, 1, 1, 1, 2])