In [1]:
import numpy as np

## One dimensional indexing

In [2]:
one_dim_array = np.arange(11)

In [3]:
one_dim_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
one_dim_array[0] # first

0

In [7]:
one_dim_array[-1] # last

10

In [9]:
one_dim_array[2::2]

array([ 2,  4,  6,  8, 10])

## Two dimensional indexing

In [11]:
two_dim_array = np.arange(10)

In [12]:
two_dim_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
two_dim_array.size

10

In [14]:
two_dim_array.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
two_dim_array = two_dim_array.reshape((5,2))

In [17]:
two_dim_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [20]:
two_dim_array[1:3] # indexing through rows

array([[2, 3],
       [4, 5]])

In [22]:
two_dim_array[1:3, 0]  # indexing through rows + takingthe 1st item

array([2, 4])

In [24]:
two_dim_array[::-1] # reversing the array

array([[8, 9],
       [6, 7],
       [4, 5],
       [2, 3],
       [0, 1]])

In [25]:
two_dim_array[::-1, ::-1]

array([[9, 8],
       [7, 6],
       [5, 4],
       [3, 2],
       [1, 0]])

# 1.

In [31]:
array_1d = np.arange(10, 21)

In [32]:
array_1d[3]

13

# 2.

In [33]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [35]:
array_2d[1, 2]

6

# 3.

In [36]:
array_1d = np.arange(10)

In [38]:
array_1d[2:6]

array([2, 3, 4, 5])

# 4.

In [39]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [42]:
array_2d[:2, -2:]

array([[2, 3],
       [5, 6]])