In [1]:
import numpy as np

In [2]:
two_dim_array = np.arange(0, 25)

In [3]:
two_dim_array = two_dim_array.reshape((5, 5))

In [4]:
two_dim_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# The mean

In [5]:
numbers = np.array([1,2,3,4,5])

In [6]:
numbers.mean()

3.0

In [8]:
two_dim_array.mean(axis=0)

array([10., 11., 12., 13., 14.])

In [7]:
two_dim_array.mean(axis=1)

array([ 2.,  7., 12., 17., 22.])

# Sorting

In [9]:
two_dim_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Swapping

In [10]:
two_dim_array[[0, 1]] = two_dim_array[[1, 0]]

In [11]:
two_dim_array

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])